name: Automação GoFile

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Atualizado para 3.10 para melhor compatibilidade

      - name: Instalar Dependências
        run: |
          # Adicionamos o undetected-chromedriver para bater com o seu import
          pip install selenium undetected-chromedriver 
          sudo apt-get update
          # Instalando dependências de sistema para o Chrome rodar em modo "headless"
          sudo apt-get install -y libnss3 libnspr4 libgbm1 libasound2 google-chrome-stable

      - name: Rodar Script
        run: python extrair_selenium.py

      - name: Salvar Log e Debug (Screenshot)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log-e-debug
          # Salvamos o log e um print da tela (caso o script gere um em erro)
          path: |
            videos_processados.txt
            *.png
