name: Renovacao GoFile 3 Dias

on:
  schedule:
    - cron: '0 0 */3 * *' # Executa à meia-noite a cada 3 dias
  workflow_dispatch: # Permite que você clique em um botão para rodar agora

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install selenium

      - name: Run Script
        env:
          GOFILE_TOKEN: ${{ secrets.GOFILE_TOKEN }}
        run: python extrair_selenium.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: links-extraidos
          path: |
            links_gofile_profundo.txt
            historico_pastas.txt
