name: Gofile Automator

on:
  schedule:
    - cron: '0 0 */2 * *' # Roda à meia-noite a cada 2 dias
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Executar Automação
        run: python script.py

      - name: Upload de Print em caso de erro
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-erro
          path: |
            error_screen.png
            fatal_error.png
