name: Gofile Automator

on:
  schedule:
    - cron: '0 0 */2 * *' # Roda a cada 48 horas
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Playwright e Stealth
        run: |
          pip install playwright playwright-stealth
          playwright install chromium --with-deps

      - name: Executar Script
        run: python script.py

      - name: Salvar Prints em caso de falha
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-debug
          path: "*.png"
